[project]
name = 'Multidimensional-Art-Curation-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.artwork-creation]
path = 'contracts/artwork-creation.clar'
clarity_version = 2
epoch = 2.5

[contracts.curation-process]
path = 'contracts/curation-process.clar'
clarity_version = 2
epoch = 2.5

[contracts.dimension-bridging]
path = 'contracts/dimension-bridging.clar'
clarity_version = 2
epoch = 2.5

[contracts.exhibition-management]
path = 'contracts/exhibition-management.clar'
clarity_version = 2
epoch = 2.5

[contracts.multidimensional-art-nft]
path = 'contracts/multidimensional-art-nft.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
